---
name: module3_task1
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup
        run: .github/scripts./setup.sh
      - name: build
        run: |
          make help
          make build
          make clean
          make POST_NAME=who-are-we POST_TITLE="Who are we" post
        working-directory: module3_task1