---
name: module3_task0
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd module3_task0
      - run: make help
        working-directory: module3_task0
