name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://github.com/MathysWaelter/holbertonschool-validation.git
      - run: cd holbertonschool-validation/module1_task4
      - run: make help
